### ISSUE TITLE
zeroconf (1)

### ISSUE THREAD

**Issue by nerohmot** [Semi-ATE/spyder-remote#1]
### Tasks

Take the time to familiarize yourself with the [zeroconf](https://github.com/jstasiak/python-zeroconf) library.

I would like to use this library because:
  - it is compatible with both `Bonjour` and `Avahi` **but doesn't depend on either of them**. (~portability)
  - the eventloop is build in (~ease of use)
  - is pure python (`noarch` ~ portability)

Do so by playing with -,  and improving on [discoverer.py](https://github.com/Semi-ATE/spyder-remote/blob/master/spyder_remote/client/discover.py) (client side) and [publish.py]() (server side).

Points of attention:
  -  `re-publish`. A `publish` is done with a (default) TTL (**T**ime **T**o **L**ive), before this time expires we need to re-publish automatically.
  -  if our server side is going down, an `un-publish` **HAS** to be done, so the clients can pick up on it. (not sure if `__del__` suffices, maybe we need also [atexit](https://docs.python.org/3/library/atexit.html)?) 
  -  by default `zeroconf` publishes on **all** local interfaces ... not sure if that is a good idea ... maybe we should only publish on the active external interfaces (and maybe the local loopback) ... needs some more thinking ... in any case, if you stumble over `netifaces`, that is what that is all about :wink: 

In order not to have surprises afterwards, use 2 physical boxes in your network segment, one being a Raspberry Pi 4B. 

This Raspberry Pi holds an Ubuntu 20.04 Linux (install see References below)

 References:
- [Download page for Ubuntu 20.04/Raspberry Pi](https://ubuntu.com/download/raspberry-pi) ➜ use the 64 Bit version as the tester will also have the 64 Bit version!
- [Best active cooling case](https://joy-it.net/en/products/RB-ALUcase+07FAN) for Raspberry Pi 4b (tried many, this is the best one, especially if you overclock)
- [Ubuntu 20.04 Install on RPi 4b video](https://www.youtube.com/watch?v=8PU1LMOu43U)
- our [conda install procedure](https://github.com/Semi-ATE/spyder-remote/blob/master/docs/conda_install_procedure.md) for RPi and later the tester.

### Versions checklist

* Spyder version: >= 5
* Python version: 3.7, 3.8
* Qt version: all
* PyQt version: all 
* Operating System name/version:
  - server : Ubuntu 20.04 Linux (aarch64 on RPI)
  - client : Windows(1)/Linux(2)/macOS(3)

**Comment by goanpeca** [comment]
Could you provide some feedback on actionable actions in terms of what has been already done and what has been missing?

**Comment by goanpeca** [comment]
Priority for client is Windows
Priority for server is Ubuntu 20.04 Linux (aarch64 on RPI)

**Comment by goanpeca** [comment]
Setup system: 1 day
Play with client/server : 2-3 days
