### ISSUE TITLE
spyder-remote (2)

### ISSUE THREAD

**Issue by nerohmot** [Semi-ATE/spyder-remote#2]
### Tasks

Let's try to stick to only **one** entry in the `IPython Console` hamburger, and fit everything in the `New Remote Console` entry point.

![image](https://user-images.githubusercontent.com/3516972/89128837-bc0a7000-d4f8-11ea-9c09-aad6527fa05d.png)

Once the (only) entry point is selected, we are presented with the following dialog:

![image](https://user-images.githubusercontent.com/3516972/89128881-f8d66700-d4f8-11ea-8c00-0209d5efa2b5.png)

At first, the `spyderHosts` QComboBox current item is empty, but the drop-down list is filled with all systems we find on zeroconf.
`Credentials` and `Conda` QGroupBox-es are disabled.

The user has no other option then to select a remote spyder host. Once he did do so, the `Credentials` QGroupBox enables. 

The `user` QCombobox is filled with: 
  - a list of all users we logged into this remote host with in the past
  - if the remote host has `guest account` enabled, this one is also in the list.
  - the last used user is the current item.

The `password` QLineEdit initially will read 'from keyring' in the placeholder text. (as the keyring will know the last password we used). If keyring is disabled (`keyring` QCheckBox is unchecked) the placeholder text is empty (indicating we need a password)
If keyring is enabled, but the `user` has nothing in the keyring, again the placeholder text is empty.

As soon as user and password are supplied, a login attempt will be made to see if login/password is valid. If not, the feedback line notifies the user that login/password is invalid. If it is valid, the `Conda` QGroupBox enables. 

The `condaEnvironments` QComboBox will be filled with the available conda environments for the logged in user. (note that conda is guaranteed to exist, as the whole system is installed over conda, however we can in principle log in with a username that is not added to the `conda` group on the remote system ... in such case the `Conda` QGroupBox is deactivated, and the feedback line states that the user isn't 'conda-enabled'.

If the user is the gues-user, the `condaEnvironments` QComboBox is filled with the environments made available over zeroconf (so some enviroments can be excluded!).

By default the `condaEnvironments` QComboBox-es current item is the project name (if a project is open), if no project is open, the current item is an empty string. It is possible that the user can define another environment name.

If a project is open, the plugin will look for a `requirements` folder in the root of the project. If it is found, the `requirements` QComboBox is filled with the entries found there. if a requirements file is present that starts with `run`, then that one is activated (made the current item). In case of multiple files that start with `run`, we are again in the case where none is made the current item. 

The `findRequirements` QToolButton (text is '...') presents us with a default -search-for-a-file- dialog, with which one can search the file system for a requirements file.

if the 'Connect' Button is clicked, the filled-in info is transmitted to the remote host, and he will:
1. if the given conda environment doesn't exist:
  - activate the base envirionment
  - execute : `conda create -n` + the python version if available in the REQUIREMENTS_FILE
2. execute:
  - execute : `conda install -n <ENVIRONMENT> --file <REQUIREMENTS_FILE>
  - execute : `conda activate <ENVIRONMENT> 
  - execute : `jupyter --runtime-dir` and recuperate the RUNTIME_DIR from the stdout.
  - execute : `python -m spyder_kernels.console` and recuperate the name from the .json file mentioned on the stdout.
  - send the .json file from the RUNTIME_DIR to the client
3. the client will do the necessary with the .json to connect transparently to the remote spyder console.

any errors from the remote side are also transmitted to the client side to be displayed. If no errors, the dialog closes and the remote console becomes available.

Notes:
  - All login's need saving in the user's spyder config (~/.config/...) for future use.
  - PLEASE :pray:  use the `.ui` and in the code the `uic` to compile & load the dialog dynamically (iow: don't construct the dialog by hand)
 
References:
- https://docs.spyder-ide.org/ipythonconsole.html

Task:
- client side (UI that communicates with the server side and starts the remote IPython Console, as a plugin)
- server side (as a process)

### Versions checklist

* Spyder version: >= 5
* Python version: 3.7, 3.8
* Qt version: all
* PyQt version: all 
* Operating System name/version:
  - server : Ubuntu 20.04 Linux (aarch64 on RPI)
  - client : Windows/Linux/macOS

**Comment by goanpeca** [comment]
I would probably split this into two parts. The "frontend" Spyder side work and the backend work. The frontend work is straightforward. I would need some extra info on what is missing on the backend to be able to hook to this.

Maybe even the frontend work can be done using dummy methods on the backend that result what we expect, that way we can make progress independently.
