### ISSUE TITLE
New entries are not added in the IPython Console hamburger

### ISSUE THREAD

**Issue by AlmoniPloni** [Semi-ATE/spyder-remote#26]
### Tasks/Steps/Elements

I've just installed the latest version of Spyder (5.0.0a3) with the spyder-remote-client plugin.
However, I don't see the two new entries in the IPython Console hamburger.

Could you please help me to resole this ?

### Versions checklist
[conda5_env.txt](https://github.com/Semi-ATE/spyder-remote/files/5791591/conda5_env.txt)

* Spyder version:  5.0.0a3
* Python version: 3.9.1
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version:
  - server : Ubuntu 20.04 Linux (aarch64 on RPI)
  - client : Windows

**Comment by goanpeca** [comment]
Entries are not yet added to that menu, they appear in the `Console` Menu
