### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by nerohmot** [Semi-ATE/spyder-remote#27]
Reproducing the failure:

When launching the spyder-remote-server, and on my local machine opening spyder (dependencies see below), I do 
Console/new remote console.
The popup nicely detects my remote host (Tom's RPi) and the guest account

![image](https://user-images.githubusercontent.com/3516972/138056214-de8e78a3-7caf-46b2-8325-061f4d377f98.png)

but if I now click `connect` I get the below message :

![image](https://user-images.githubusercontent.com/3516972/138114665-4c3d78f8-2205-42d8-a6ca-ea0f02e0d40b.png)

Note : we install python no longer with anaconda, but with maxiconda as per www.maxiconda.org

* I added the GUEST user, with password GUEST (all in capital, had to add the --force-badname flag to do so)
* I installed maxiconda for the GUEST user
* I installed maxiconda for the root user, and in the `base` environment I also installed `spyder-remote-server`
* I did a `sudo su root`, install the deamon with a `spyder-remote-server install GUEST`
* I started the deamon from a root prompt with `spyder-remote-server start`

### Spyder dependencies 

# Mandatory:
atomicwrites >=1.2.0                      :  1.4.0 (OK)
chardet >=2.0.0                           :  4.0.0 (OK)
cloudpickle >=0.5.0                       :  2.0.0 (OK)
cookiecutter >=1.6.0                      :  1.7.3 (OK)
diff_match_patch >=20181111               :  20200713 (OK)
intervaltree >=3.0.2                      :  3.0.2 (OK)
IPython >=7.6.0                           :  7.27.0 (OK)
jedi >=0.17.2;<0.19.0                     :  0.18.0 (OK)
jsonschema >=3.2.0                        :  3.2.0 (OK)
keyring >=17.0.0                          :  23.2.1 (OK)
nbconvert >=4.0                           :  6.1.0 (OK)
numpydoc >=0.6.0                          :  1.1.0 (OK)
paramiko >=2.4.0                          :  2.7.2 (OK)
parso >=0.7.0;<0.9.0                      :  0.8.2 (OK)
pexpect >=4.4.0                           :  4.8.0 (OK)
pickleshare >=0.4                         :  0.7.5 (OK)
psutil >=5.3                              :  5.8.0 (OK)
pygments >=2.0                            :  2.10.0 (OK)
pylint >=2.5.0;<2.10.0                    :  2.9.6 (OK)
pyls_spyder >=0.4.0                       :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0                      :  1.2.2 (OK)
pylsp_black >=1.0.0                       :  None (OK)
qdarkstyle =3.0.2                         :  3.0.2 (OK)
qstylizer >=0.1.10                        :  0.2.1 (OK)
qtawesome >=1.0.2                         :  1.0.3 (OK)
qtconsole >=5.1.0                         :  5.1.1 (OK)
qtpy >=1.5.0                              :  1.11.1 (OK)
rtree >=0.9.7                             :  0.9.7 (OK)
setuptools >=49.6.0                       :  58.0.4 (OK)
sphinx >=0.6.6                            :  4.2.0 (OK)
spyder_kernels >=2.1.1;<2.2.0             :  2.1.1 (OK)
textdistance >=4.2.0                      :  4.2.1 (OK)
three_merge >=0.1.1                       :  0.1.1 (OK)
watchdog >=0.10.3                         :  2.1.5 (OK)
zmq >=17                                  :  22.3.0 (OK)

# Optional:
cython >=0.21                             :  0.29.24 (OK)
matplotlib >=2.0.0                        :  3.4.3 (OK)
numpy >=1.7                               :  1.21.2 (OK)
pandas >=1.1.1                            :  1.3.3 (OK)
scipy >=0.17.0                            :  1.7.1 (OK)
sympy >=0.7.3                             :  1.8 (OK)

# Spyder plugins:
ATE.spyder.plugin 0.1.27                  :  0.1.27 (OK)
spyder_remote_client.spyder.plugin 0.0.24 :  0.0.24 (OK)
spyder_screencast.plugin 0.0.17           :  0.0.17 (OK)
spyder_terminal.terminalplugin 1.1.0      :  1.1.0 (OK)

**Comment by nerohmot** [comment]
Once I got the `spyder remote server not responding`, and I go back to the RPi, the daemon is no longer running as it states `deamon not started` when I want to stop the deamon ...
Looked for loggings, but didn't find anything ...

**Comment by nerohmot** [comment]
I also noted that I can't enter another than the GUEST account (the one published), and the password field is not accessable.
I concluded that

**Comment by nerohmot** [comment]
woops, wrong button

**Comment by nerohmot** [comment]
@goanpeca 
Looked through the sources, and discovered that there is a logfile ...
However this is filled with always the same : "Fork successfull" 
There is a bunch of print statements, maybe better to move them to the logging ;-)
Maybe we need an atexit thingy to capture death (and log the stacktrace) ?

**Comment by seimit** [comment]
Hi
I enabled the internal console and saw that a message to spyder-remote-server was sent, but json data answer is null.
![spyder-remote](https://user-images.githubusercontent.com/77433609/138498998-0021b26c-2e4b-40e6-9023-fd17275adcc1.png)
