### ISSUE TITLE
package building (5)

### ISSUE THREAD

**Issue by nerohmot** [Semi-ATE/spyder-remote#3]
### Tasks

This Repo holds 2 conda packages:
- spyder-remote-server
- spyder-remote-client

`spyder-remote-client` is a straight forward package implementing a spyder plugin.

`spyder-remote-server` is a bit different, in that it provides a script (in <env>/bin or something like that)
so that one installs and enables the package as follows:
```
(base) me@mybox:~$ conda install spyder-remote-server
(base) me@mybox:~$ sudo spyder-remote-server --install
```
### Prerequisites
  - [Issue#1](https://github.com/Semi-ATE/spyder-remote/issues/1) : `zeroconf` needs to be finished
  - [issue#2](https://github.com/Semi-ATE/spyder-remote/issues/2) : `spyder-remote` needs to be finshed
  - [Issue#4](https://github.com/Semi-ATE/spyder-remote/issues/4) : `spyder-remote-server daemon` needs to be finished
  - [Issue#5](https://github.com/Semi-ATE/spyder-remote/issues/5) : `spyder-remote-server script` needs to be finished

Anyway this `task` is to build the 2 packages.

### Versions checklist

* Spyder version: >= 5
* Python version: 3.7, 3.8
* Qt version: all
* PyQt version: all 
* Operating System name/version:
  - server : Ubuntu 20.04 Linux (aarch64 on RPI)
  - client : Windows/Linux/macOS

**Comment by goanpeca** [comment]
This should be about a day of actual work, including setting up CI to automate the release process and setting the PyPI/conda-forge workflows plus release documentation. But this sometimes takes a bit longer due to time needed on conda-forge for things ti be approved etc. 

2 Days.
