### ISSUE TITLE
spyder-remote-server daemon (3)

### ISSUE THREAD

**Issue by nerohmot** [Semi-ATE/spyder-remote#4]
### Tasks/Steps/Elements 

The server-side is first implemented as a normal process, and then turned into a daemon.

Our first concern is that it runs on Linux, so one could use the `stevens.py` template, but for future compatibility to macOS and Windows, maybe there are better ways (read: libraries).

Task:
  - wrap the server-side `process` (from [issue#2](https://github.com/Semi-ATE/spyder-remote/issues/2)) into a daemon process

### Versions checklist

* Spyder version: >= 5
* Python version: 3.7, 3.8
* Qt version: all
* PyQt version: all 
* Operating System name/version:
  - server : Ubuntu 20.04 Linux (aarch64 on RPI)
  - client : Windows/Linux/macOS

**Comment by goanpeca** [comment]
- What is the `stevens.py` template 🙃 ?
- is the daemon configurable?
- what are the configuration options?
- The actual daemon (is anything on this side already done)
- The actual process that the daemon runs is another, (What is missing from what is currently done?)

Time: 1-3 days ?

**Comment by nerohmot** [comment]
deaemoniker : https://daemoniker.readthedocs.io/en/latest/
python-daemon : https://pypi.org/project/python-daemon/
... system-d stuff ?
