### ISSUE TITLE
spyder-remote-server script (4)

### ISSUE THREAD

**Issue by nerohmot** [Semi-ATE/spyder-remote#5]
### Tasks/Steps/Elements 

This is the `task` to make a (bash or maybe better python) script that installs the `spyder-remote-server` daemon on the OS.

We are at this point in time only interested in Linux, and specifically Ubuntu 20.04. (other Linuxes that might be a bit different have to be added in `community work`)

```sh
(SCT) me@mybox:~$ conda install spyder-remote-server
... 
(SCT) me@mybox:~$ sudo spyder-remote-server --install
...
(SCT) me@mybox:~$ sudo spyder-remote-server --uninstall
```

### Versions checklist

* Spyder version: >= 5
* Python version: 3.7, 3.8
* Qt version: all
* PyQt version: all 
* Operating System name/version:
  - server : Ubuntu 20.04 Linux (aarch64 on RPI)
  - client : Windows/Linux/macOS

**Comment by goanpeca** [comment]
This should also probably be split so that we can work independently. On one side a script that will install a daemon for a dummy service so we can test things are working as expected.

Time: 1-2 days (depending on cross-platform compatibility)
