### ISSUE TITLE
further github actions (6)

### ISSUE THREAD

**Issue by nerohmot** [Semi-ATE/spyder-remote#6]
### Tasks

all github actions stuff that is not included in [issue#3 : package building](https://github.com/Semi-ATE/spyder-remote/issues/3) 

- commit & PR test stuff
- release stuff (pypi & feedstock)

**TBD:** What PyPi account will we use ?!?

### Versions checklist

* Spyder version: >= 5
* Python version: 3.7, 3.8
* Qt version: all
* PyQt version: all 
* Operating System name/version:
  - server : Ubuntu 20.04 Linux (aarch64 on RPI)
  - client : Windows/Linux/macOS

**Comment by nerohmot** [comment]
added a SemiconductorATE@gmail.com account, and linked a PiPy account (Semi-ATE) to it :+1:

**Comment by goanpeca** [comment]
Awesome, that sounds like a good idea to keep things separate, and also to delegate the publishing work if needed.

This should be pretty straightforward and as you mention partly touches on the packaging work infrastructure which will also add some automation. 

I would limit this to handle all testing in all the needed platforms plus coverage and make sure all things are running.

Time: 0.5 days

**Comment by goanpeca** [comment]
@nerohmot I created the packages with my account since there seemed to be some issues. But we can now have things set on Monday with this account.
