### ISSUE TITLE
Time Estimation & Quotation

### ISSUE THREAD

**Issue by nerohmot** [Semi-ATE/spyder-remote#7]
### Time Estimation & Quotation

1. [zeroconf](https://github.com/Semi-ATE/spyder-remote/issues/1) : 1d + 3d 
2. [spyder-remote](https://github.com/Semi-ATE/spyder-remote/issues/2) : 1d + 3d
3. [spyder-remote-server daemon](https://github.com/Semi-ATE/spyder-remote/issues/4) : 1d + 1d 
4. [spyder-remote-server script](https://github.com/Semi-ATE/spyder-remote/issues/5) : 1d
5. [package building](https://github.com/Semi-ATE/spyder-remote/issues/3) : 1d
6. [further github actions](https://github.com/Semi-ATE/spyder-remote/issues/6) : 1d
7. **documentation** : 0d †

@rgommers : 13 days @ 8h = 104h 

† The only documentation that is needed is the README.md in the project root, that outlines installation. The documentation how to use it will be made in video format (=test of the QScreenCast plugin)

@rgommers ,

Please remember the `new` process :
  - QuanSight emails me (tom.hoeren@micronas.com) the **Quote**. The Quote holds the following info: 
    - a <ins>reference number</ins> (=your reference)
    - the <ins>email address where to send the PO</ins> (**P**urchase **O**rder)
    - the <ins>individual points</ins> (like above #1..#6)with each time the amount for each point ➜ in this case it is not so important, but for future projects you can do partial invoices, just stating for which points the invoice is :smile: 
  - I put your **Quote** it in our system, and about 10 days later you will receive our **PO** (from our purchasing department) <ins>in the stated email address of the Quote</ins>. The **PO** holds the following info:
    - The <ins>PO number</ins> (=our reference)
    - The <ins>Quote number</ins> (=your reference)
    - The <ins>ordered items</ins> (like above #1..#6)
    - The <ins>email address where the Invoice should go to</ins>.
  - Upon reception of the **PO** QuanSignt sends a **Confirmation** to the email address where the **Invoice** should go to.
  - When (partial) work is done, you just send your **Invoice** to the email address stated in the **PO**. (so the **same** address that also received the **PO Confirmation**!) The **Invoice** holds the following info:
    - The <ins>PO number</ins>.
    - The <ins>ordered items</ins> to be settled.
  - The **Invoice** will pop-up in my SAP account for approval, I press the button, and the payment is released (after some other people also pressed their buttons, but as long as I stay in budget, that is a formality)

**Comment by rgommers** [comment]
The estimates look reasonable, thanks @nerohmot and @goanpeca. I'm just trying to figure out how to get this put on a piece of paper now.
